version: "2"

services:
  p-straw-hat:
<<<<<<< HEAD
    image: gcr.io/doctor-tribehired/team6app:latest
=======
    image: gcr.io/poneglyph/p-straw-hat:latest
>>>>>>> 23674a658bfd40ec6f4dd2cbb00030f4342cb55d
    build:
      context: .
      dockerfile: dockerfiles/app.docker
    env_file: .env
    container_name: "p-straw-hat"
    working_dir: /usr/src/app
    ports:
      - "50050:50050"
