version: "2"

services:
  p-straw-hat:
    image: gcr.io/doctor-tribehired/team6app:latest
    build:
      context: .
      dockerfile: dockerfiles/app.docker
    env_file: .env
    container_name: "team6app"
    working_dir: /usr/src/app
    ports:
      - "5000:50050"
