version: "2"

services:
  p-straw-hat:
    image: gcr.io/staging-256810/p-straw-hat:latest
    build:
      context: .
      dockerfile: dockerfiles/app.docker
    env_file: .env
    container_name: "p-straw-hat"
    working_dir: /usr/src/app
    ports:
      - "50050:50050"
